[platformio]
default_envs = usbtiny

[env:usbtiny]
platform = atmelavr
board = ATmega1284P
framework = arduino
board_build.f_cpu = 8000000L
board_hardware.oscillator = internal
board_hardware.bod = disabled
board_hardware.eesave = yes
board_hardware.uart = uart0
board_hardware.pinout = standard

upload_protocol = usbtiny
upload_flags = -B 10

monitor_speed = 9600

lib_deps =
[env:fuses_bootloader]
platform = atmelavr
board = ATmega1284P
framework = arduino
upload_protocol = usbtiny
; Using MightyCore settings
board_build.f_cpu = 8000000L
board_hardware.oscillator = internal
board_hardware.bod = disabled
board_hardware.eesave = yes
board_hardware.uart = uart0
board_hardware.pinout = standard


; pio run -e fuses_bootloader -t bootloader